"""
Renderers: the threat model as artifacts a reviewer can read and diff.

  render_dfd()       Mermaid data-flow diagram. One subgraph per trust zone,
                     boundary-crossing flows drawn thick and red, attacker
                     entry points (from the attack tree) as dashed arrows.
  render_controls()  Markdown control checklist, risk-ranked. Post 17's
                     red-team ticks these boxes; see checklist.py.
  render_threats()   Markdown threat register with a STRIDE-per-element view.
  lint_mermaid()     A small structural check so tests can assert the diagram
                     is plausible Mermaid without a Mermaid install.
  write_all()        Writes everything into out/.
"""

from __future__ import annotations

import json
import os
import re

from attack_tree import Node, render_mermaid as tree_mermaid, render_text as tree_text
from model import STRIDE, STRIDE_PER_ELEMENT, ThreatModel
from owasp import ALL_OWASP
from risk import rank_controls

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "out")

_SHAPES = {
    "external": ('(["', '"])'),   # stadium
    "process": ('["', '"]'),      # rectangle
    "datastore": ('[("', '")]'),  # cylinder
}


def _node(c) -> str:
    open_, close = _SHAPES[c.kind]
    return f"{c.id}{open_}{c.name}{close}"


def render_dfd(m: ThreatModel, tree: Node | None = None) -> str:
    lines = [
        "%% Build It, Break It, Become It -- Act II: the reference architecture, threat-modeled",
        "%% Generated by labs/07-threat-model/render.py. Do not edit by hand.",
        "%% Subgraphs are trust zones; thick red edges cross a trust boundary;",
        "%% dashed edges from ATTACKER are attack-tree entry points.",
        "flowchart LR",
    ]
    for z in sorted(m.zones, key=lambda z: z.trust):
        members = [c for c in m.components if c.zone == z.id]
        if not members:
            continue
        lines.append(f'    subgraph Z_{z.id}["{z.name} -- trust {z.trust}"]')
        lines += [f"        {_node(c)}" for c in members]
        lines.append("    end")
    unzoned = [c for c in m.components if c.zone is None]
    for c in unzoned:
        lines.append(f"    {_node(c)}")

    edge_index = 0
    crossing_edges = []
    for f in m.flows:
        lines.append(f'    {f.src} -->|"{f.id}: {f.data}"| {f.dst}')
        if m.crosses_boundary(f):
            crossing_edges.append(edge_index)
        edge_index += 1

    attack_edges = []
    if tree is not None:
        entries = {}
        for leaf in tree.leaves():
            if leaf.entry and m.component(leaf.entry):
                entries.setdefault(leaf.entry, []).append(leaf.id)
        if entries:
            lines.append('    ATTACKER{{"Attacker"}}')
            for comp, leaf_ids in entries.items():
                lines.append(f'    ATTACKER -.->|"{", ".join(leaf_ids)}"| {comp}')
                attack_edges.append(edge_index)
                edge_index += 1

    if crossing_edges:
        lines.append("    linkStyle " + ",".join(map(str, crossing_edges))
                     + " stroke:#c0392b,stroke-width:2.5px")
    if attack_edges:
        lines.append("    linkStyle " + ",".join(map(str, attack_edges))
                     + " stroke:#8e44ad,stroke-dasharray:4 3")
    if unzoned:
        lines.append("    classDef unzoned fill:#fff3cd,stroke:#e67e22,stroke-dasharray:5 3")
        lines.append("    class " + ",".join(c.id for c in unzoned) + " unzoned")
    if tree is not None and attack_edges:
        lines.append("    classDef attacker fill:#2c3e50,color:#fff")
        lines.append("    class ATTACKER attacker")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# A structural lint for Mermaid flowcharts
# --------------------------------------------------------------------------- #
_ID = r"[A-Za-z][A-Za-z0-9_]*"
_EDGE = re.compile(rf"^\s*({_ID})\s*(?:-->|-\.->)\s*(?:\|[^|]*\|\s*)?({_ID})\s*$")
_DEF = re.compile(rf"^\s*({_ID})\s*(\(\[|\[\(|\[|\{{\{{|\{{|\()")
_RESERVED = {"end", "subgraph", "graph", "flowchart", "class", "classDef", "linkStyle"}


def lint_mermaid(text: str) -> list[str]:
    """Return a list of problems (empty = plausible). Not a full parser."""
    problems = []
    lines = [ln for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("%%")]
    if not lines or not lines[0].strip().startswith(("flowchart", "graph")):
        problems.append("first statement must be 'flowchart' or 'graph'")
    depth, defined, edges, n_edges = 0, set(), [], 0
    for ln in lines[1:]:
        s = ln.strip()
        if s.startswith("subgraph "):
            depth += 1
            continue
        if s == "end":
            depth -= 1
            if depth < 0:
                problems.append("'end' without matching 'subgraph'")
            continue
        if s.startswith(("classDef ", "class ", "linkStyle ")):
            if s.startswith("linkStyle "):
                for idx in s.split()[1].split(","):
                    if not idx.isdigit():
                        problems.append(f"bad linkStyle index {idx!r}")
                    edges.append(("__link__", int(idx) if idx.isdigit() else -1))
            continue
        e = _EDGE.match(s)
        if e:
            edges.append((e.group(1), e.group(2)))
            n_edges += 1
            continue
        d = _DEF.match(s)
        if d:
            nid = d.group(1)
            if nid in _RESERVED:
                problems.append(f"node id {nid!r} is a Mermaid keyword")
            defined.add(nid)
            # brackets inside a node definition must balance
            body = s[len(nid):]
            for o, c in ("[]", "()", "{}"):
                if body.count(o) != body.count(c):
                    problems.append(f"unbalanced {o}{c} in definition of {nid}")
            continue
        problems.append(f"unrecognized statement: {s[:60]}")
    if depth != 0:
        problems.append(f"{depth} unclosed subgraph(s)")
    for a, b in edges:
        if a == "__link__":
            if not 0 <= b < n_edges:
                problems.append(f"linkStyle index {b} out of range (edges: {n_edges})")
            continue
        for nid in (a, b):
            if nid not in defined:
                problems.append(f"edge references undefined node {nid}")
    return problems


# --------------------------------------------------------------------------- #
# Markdown artifacts
# --------------------------------------------------------------------------- #
def render_controls(m: ThreatModel) -> str:
    ranked = rank_controls(m)
    lines = [
        "# Control checklist -- reference agent architecture",
        "",
        "Generated by `labs/07-threat-model/render.py` from the threat model. Do not edit by",
        "hand: change `reference_model.py` and re-run `python run_demo.py`.",
        "",
        "Ranked by the highest likelihood x impact among the threats each control treats",
        "(illustrative scoring, 1-25). The Post 17 red-team ticks a box only when an attack",
        "that targets the control has been run and driven to ~0% success.",
        "",
        "| Rank | | Control | Score | Treats | OWASP | Verify in |",
        "|---:|:-:|---|---:|---|---|---|",
    ]
    for r in ranked:
        lines.append(f"| {r.rank} | [ ] | **{r.id}** {r.name} | {r.score} | "
                     f"{', '.join(r.threats)} | {', '.join(r.owasp)} | "
                     f"{', '.join(r.verify_in)} |")
    lines += ["", "## Checklist", ""]
    for r in ranked:
        c = m.control(r.id)
        lines.append(f"- [ ] **{r.id}** {r.name} (score {r.score}) -- {c.description}")
    if m.owasp_accepted:
        lines += ["", "## Explicitly accepted OWASP items", ""]
        for item, reason in sorted(m.owasp_accepted.items()):
            lines.append(f"- **{item} {ALL_OWASP.get(item, '')}** -- {reason}")
    return "\n".join(lines) + "\n"


def render_threats(m: ThreatModel) -> str:
    lines = ["# Threat register", "",
             "| Id | STRIDE | Threat | Targets | L | I | Risk | Controls | OWASP | ATLAS tactic |",
             "|---|:-:|---|---|:-:|:-:|:-:|---|---|---|"]
    for t in sorted(m.threats, key=lambda t: (-t.risk, t.id)):
        targets = ", ".join(t.targets) if len(t.targets) <= 4 else f"{len(t.targets)} flows"
        lines.append(f"| {t.id} | {t.stride} | {t.title} | {targets} | {t.likelihood} | "
                     f"{t.impact} | {t.risk} | {', '.join(t.controls)} | "
                     f"{', '.join(t.owasp)} | {', '.join(t.atlas)} |")
    lines += ["", "## STRIDE per element", "",
              "Each cell is the number of threats recorded for that letter. `n/a` = letter does",
              "not apply to this element type; `na*` = considered and ruled out with a reason.", "",
              "| Element | Kind | " + " | ".join(STRIDE) + " |",
              "|---|---|" + ":-:|" * len(STRIDE)]
    elements = [(c.id, c.kind) for c in m.components] + [(f.id, "flow") for f in m.flows]
    for eid, kind in elements:
        cells = []
        for letter in STRIDE:
            if letter not in STRIDE_PER_ELEMENT[kind]:
                cells.append("n/a")
            elif (eid, letter) in m.stride_na:
                cells.append("na*")
            else:
                cells.append(str(len(m.threats_on(eid, letter))))
        lines.append(f"| {eid} | {kind} | " + " | ".join(cells) + " |")
    if m.stride_na:
        lines += ["", "Ruled out:", ""]
        for (eid, letter), reason in sorted(m.stride_na.items()):
            lines.append(f"- `{eid}` {STRIDE[letter][0]}: {reason}")
    return "\n".join(lines) + "\n"


def write_all(m: ThreatModel, tree: Node, implemented: set[str],
              out_dir: str = OUT_DIR, suffix: str = "") -> dict[str, str]:
    """Write every artifact; return {name: path}."""
    os.makedirs(out_dir, exist_ok=True)
    files = {
        f"architecture-threats{suffix}.mmd": render_dfd(m, tree),
        f"attack-tree{suffix}.mmd": tree_mermaid(tree, implemented),
        f"attack-tree{suffix}.txt": tree_text(tree, implemented) + "\n",
        f"controls{suffix}.md": render_controls(m),
        f"threats{suffix}.md": render_threats(m),
    }
    from checklist import checklist_from_model
    files[f"controls{suffix}.json"] = json.dumps(
        [item.__dict__ for item in checklist_from_model(m)], indent=2) + "\n"
    paths = {}
    for name, text in files.items():
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        paths[name] = path
    return paths
